apiVersion: apps/v1
kind: Statefulset
metadata: 
 name: nginx
spec:
 selector:
  matchLabels:
   app: nginx
serviceName: nginx
template: 
  metadata: 
    labels:
      app: nginx
  spec:
   conatiners:
    - name: nginx
      image: nginx:1.19-accion
      ports:
       - containerPort: 80
      volumeMounts: 
       - name: nginx-storage
         mountPath: /usr/share/nginx/myapp
      resources:
       requests:
        cpu: "256m"
        memory: "128M"
       limits:
        cpu: "512m"
        memory: "256Mi"
  volumeClaimTemplate:
   - metadata:
      name: nginx-storage
     spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
         storage: 1Gi
